enum AppReducerEventType {
  DISPLAY_BUTTON_CHILD_ONE_EXCEEDS_MAX = 'DISPLAY_BUTTON_CHILD_ONE_EXCEEDS_MAX',
  DISPLAY_BUTTON_CHILD_TWO_EXCEEDS_MAX = 'DISPLAY_BUTTON_CHILD_TWO_EXCEEDS_MAX',
};

export default AppReducerEventType;